import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
export const metadata: Metadata = {
  title: "Round",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className="font-cairo">
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
