import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Round",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta
          property="og:image"
          content="https://i.ibb.co/417VtbG/image-2024-11-25-170725886.png"
        />
      </head>
      <body className="font-cairo ">
        <NavBar />
        <main className="overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
